# Generated by Django 2.1 on 2021-02-01 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boxers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxer',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
