# Generated by Django 3.1.6 on 2021-02-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxers', '0002_boxer_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='boxer',
            name='date_of_birth',
        ),
    ]
