# Generated by Django 3.1.6 on 2021-02-06 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boxers', '0003_auto_20210205_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxer',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='boxer',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
